### PR TITLE
Provide workaround for batch xlet downloads, fix file patching, patch global.screen.get_mouse_window

### PR DESCRIPTION
**Pull request by jaszhix**
This isn't ideal, but because of it being asynchronous, using recursion
seems like the easiest way to make it work for now.

### CODE REVIEW

**Comment by lestcape** [comment]
What it's the problem that you need to do that?
If you execute a asynchronous operation, anyway you need to wait for the task to continue the processing. I will not merged this, i don' t want to have a thing that just are working with patches if we can do this better or not?

**Comment by jaszhix** [comment]
Batch xlet downloading just doesn't work. I don't see the harm in merging it, it can be changed any time. This fills in missing functionality.

**Comment by jaszhix** [comment]
When you select multiple applets, click install, it'll only download the first one. This also fixes a bug with post-install, where the checkboxes don't deselect. It also fixes it so you can download any other xlet without restarting the applet. I'm probably going to give up on this project for now if you stop merging my commits. There's too much that needs to be done.

**Comment by jaszhix** [comment]
It also seems like you introduce new regressions, and don't know that you are? I can't install some applets anymore because of imports.searchPath - the only way to work around it is put the applet in both the extension's directory, and the extension's user data directory. Applet settings have no effect for stock applets, but third party ones do. I don't know, I can't keep up with the changes/breakage, and you seem to think because I add what's just a scaffold so the thing is easier to use, its unmergable.

**Comment by jaszhix** [comment]
I've already made a concession after you removed ITM from the repo, after it being there for weeks. I really shouldn't bother with this project anymore. I put my ego aside to ensure it gets done, but I'm not going to keep fighting with you over minor code changes.

**Comment by lestcape** [comment]
You are speaking for nothing. In first place, i just read your own comment. I don' t know what happen, just i read what you say about it... and i tell you: if you say that this have problems, my reaction need to be not merged it or what supposed that this will be? Also i ask you if we can do the things better.... We can?

**Comment by jaszhix** [comment]
I didn't say this has any inherent problems, I just know there should be a better way to do it - that can be applied to a lot of things we've done with this project (i.e, string replacement). I think you're taking my PR notes too literally, I wouldn't have created the PR if it was low effort or going to introduce bugs.

No, I'm definitely speaking for _something_, and I think you are being too closed minded.

**Comment by lestcape** [comment]
Not, I'm in my work, not in my home... you pr it's not short to read it and note the problem that you mention... Of course I only read the notes and like you say that there are problems, sorry but what supposed that i need to do? Of course i will try to implemented all things in a better way, if i can. Nothing specially with this one. Also the same for you, if you found a better way fixed it, not matter.

About the path problem: yes i have not the time to see in deep what you are doing here, also this is some things that i have the intention to do, but it's ok. You are notice that change, and probably you don't know what happen... Let me explain....

**Comment by lestcape** [comment]
const USER_DOMAIN_FOLDER = '.classic-gnome';

This is the folder of our extension it's the equivalent of ~/.cinnamon folder.

const USER_CONFIG_FOLDER = 'configs';

This is where the xlet save his active configuration, it' s the equivalent of
~/.cinnamon/config

const USER_REPOSITORIES_FOLDER = 'xlet.repositories';

This is an additional folder, nothing equivalent in cinnamon and it's locate at ~/.cinnamon/xlet.repositories

const USER_CACHE_FOLDER = 'xlet.cache';

This is the equivalent of the folder:
~/.cinnamon/spices.cache


const USER_INSTALL_FOLDER = 'classic-gnome';

This is the location to install xlet in cinnamon and in a normal user configuration this folder it's locate at:
~/.local/share/cinnamon in our case in ~/.local/share/classic-gnome really it's locate at:
GLib.get_user_data_dir() + USER_INSTALL_FOLDER], because the GLib.get_user_data_dir(), not need to be ~/.local/share

const USER_LOCALE_FOLDER = 'locale';

This is for locales and we have not support yet.

Anyway it's clear for me that there are path problems, but this is because all path are harcode, so i can not find all places where i need to do a change, please help me on that, this sure will solve the issue.

**Comment by jaszhix** [comment]
Okay, I will look at it later. The only thing that bothered me was that you said no to this PR before looking at it completely. I ammending it and making changes but there were none requested so a flat no answer gets under my skin a little bit. I work from home, so I can budget my own time, but I would be making any hard decisions about things while I am working.

**Comment by lestcape** [comment]
I ask you man, in fact i don't see what you are doing. Sorry, i will take the time to see if ask without see are brothering you.

**Comment by jaszhix** [comment]
The first commit wraps the xlet downloading functions in a recursive sequence, so at the end of one file, it will continue downloading the next. The only reason I said "not ideal" is because this works against the download manager, but the original way was written in Python, and a lot of those concepts with urllib are not similar to JS, like opening files for writing, and closing them. 

The second commit adds a function needed to get stickynotes@scollins... running. Then there's a clutter error when you click the applet.

```
(gnome-shell:3500): Clutter-CRITICAL **: clutter_actor_set_child_below_sibling: assertion 'child->priv->parent == self' failed
```

 My implementation of global.screen.get_mouse_window is not correct, so I don't mind changing it, but I did mean to bring it to your attention later because you probably are more familiar with it. I added that code mainly as a placeholder so I could see what other errors surface with that extension.

Sorry about the rant, I guess I didn't understand what you were asking.

**Comment by lestcape** [comment]
I think we probably can test the efficiency of throw a lot of asynchronous real process (system process, spaw), to realize activities. But the downloaderManager, can download all files and then inform when all files are downloaded. You can process one file by one, but later than the download manager finished, don't force the download manager to do one download and then another. That it's the idea of the download manager. This implemented a lot of asynchronous calls, but will act as a semaphore, in a multithread environment.

**Comment by lestcape** [comment]
This is that lines: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/settings/spices.js#L375-L376

Just split your process in two methods and way for a download-finished signal to begin processing the files, in this case could be one by one or cloud be with an additional tool (a program), and call one instance of the external program for one file... Then you could have n instances running at the same time, and processing the xlet that was assigned... Then wait for all task to finished and inform to the page that they finished, to perform a reload of the xlet.

**Comment by jaszhix** [comment]
Ah, ok. I'm still using the download manager [here](https://github.com/jaszhix/Classic-Gnome/blob/5859fbef6bf86f437f88c8e68dd21ed5b3d4539a/classicGnome%40lestcape/settings/spices.js#L743). I tried to loop this function from the page, but because the signal id is shared it didn't work. So I might try pushing the signal id's into an array of objects - store the id, and uuid.

**Comment by lestcape** [comment]
It's clear for me that the current structure of spice, are not friendly to do that, so please feel free to change it like you want... You need to go up and split the things from the source, later you can not.

**Comment by lestcape** [comment]
Yes, but that's the problem,,, Go up out of the install function. https://github.com/jaszhix/Classic-Gnome/blob/5859fbef6bf86f437f88c8e68dd21ed5b3d4539a/classicGnome%40lestcape/settings/spices.js#L716

The install function it's designed to install one things....not we need to catch the real task, and then we can split it in several download task, then joint again all in a download finished and decide what you want to do...

**Comment by jaszhix** [comment]
Yeah, I think maybe calling ```startDownloads``` on downloadManager after we have everything queue'd up?

**Comment by lestcape** [comment]
sure... iterate for all adding it to the download task, start the download, wait to finished and iterate for all again.

**Comment by lestcape** [comment]
Don' t forget disconnect the download-finished, when finished, that's a deficiency of the model of download manager, won  have a good way to report things, we need to call clear at the begin and also disconnect the download-finished, but well.... If you find something better fix it.

**Comment by lestcape** [comment]
I think your problem was understand what i do with the download manager. The download manager don' t provide a mutithread-enviroment or just threads. This have only the ability to provide parallel downloads, but also it's not allowed add more jobs in the middle of the process. So, to use it, you need to spilt your task in jobs, and separate the download task to the other things.  The others things can not be do in parallel, we are in gjs and without threads : (

**Comment by jaszhix** [comment]
Yeah, I noticed you can't always launch two instances of the settings apps - I see this when it fails:

```
(Classic Gnome:3596): Gjs-WARNING **: JS ERROR: Error: Invalid element in string array
XLetSidePage<.load_xlet_data@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/settings/xletSettings.js:158
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
XLetSidePage<.load@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/settings/xletSettings.js:111
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Module<.on_module_selected@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/tools/modules/cg_settings.js:62
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Application<._onCommandLine@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/tools/xlet-settings.js:187
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Application<.run@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/tools/xlet-settings.js:133
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/tools/xlet-settings.js:445
```

**Comment by lestcape** [comment]
Yes, i notice the same, also the final idea will not be launch the settings as an individual application. Will be display his sidepage inside the main windows, when configured will be selected.

**Comment by lestcape** [comment]
Open tow command line, execute in want the settings and in another the settings.... In the second you can not see any thing.... We are sharing things i don't know how.

**Comment by jaszhix** [comment]
Ah, yeah, its probably launching it as a child process when we use spawn sync.

**Comment by lestcape** [comment]
Not, because i launch it in separate different command lines. In theory they are individual application. In practice, probably some libraries are shared, and one things modify the other instance, but thats it's pretty interesting...

**Comment by jaszhix** [comment]
In that case, creating immutable objects is important. I think after the dust settles and things are feature complete we can see what could be fixed, but I guess for now its relatively minor.

**Comment by lestcape** [comment]
I disagree, that it's interesting.... :) I open 2 instance with a print message... jump.... the message are printing in the same command line... when they need to be printing one for terminals.

**Comment by lestcape** [comment]
It's the application id, that need to be a dynamically string: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/tools/xlet-settings.js#L123

**Comment by lestcape** [comment]
just remove that line

**Comment by jaszhix** [comment]
Ok, I think I got it so download and install procedure are running through the downloadManager correctly.

**Comment by lestcape** [comment]
Yes, this is correctly, but they are not using the advantage of have parallel downloads. Anyway i can merged. The advantages are for a working things, not for nonworking.

**Pull request merged**
