### PR TITLE
Create global variable "cimports" for Cinnamon modules

### PR DESCRIPTION
**Pull request by jaszhix**
This will get us closer to running Cinnamon applets/extensions/etc without needing to modify their syntax.

### CODE REVIEW

**Comment by lestcape** [comment]
Thats it's what i try to do with GiRepository, but imports.gi it's hacked in gnome-shell and not allow me to do this. I want to import gi.Cinnamon. There are a way and it's modify the search path of GiRepository and add one typelib private... But i don't know how generate a typelib called cinnamon but with a reference to the Shell library instead of cinnamon.

Here the problem will be that in my opinion this code break the gnome-shell API or not? My initial idea was keep it separated and only replace the imports in the installation process, because anyway i will need to do that for gi. I don't think will be nice break the shell API, we can used it also... If we wrap the actors inside the panels as an applet class and  if we replace the panel as a cinnamon panel and then re-add the actors.

Or what you think?

**Comment by jaszhix** [comment]
Yeah, that's something I was thinking about after pushing this, if this is going to overwrite the imports object for all other Gnome Shell extensions - that wouldn't work if it does. Maybe we could give all cinnamon modules their own namespace, like imports.c.ui.dnd so there's no conflict.

**Comment by lestcape** [comment]
Another possibility to not break the api it's create a read-only property instead of the object and inside the property find the context and decide the library that we want to return base on where the current file it's.

**Comment by jaszhix** [comment]
I was thinking of adding something like node/commonjs syntax, a custom ```require``` function that does this. We would have to break the API for Cinnamon if we import via function though, right?

**Comment by lestcape** [comment]
```
 for (let key in ExtensionUtils.imports.ui) {
       try {
            if (typeof _importsUI[key] === 'undefined') {
                Object.defineProperty(_importsUI.prototype, key, {
                    get: function() {
                        if (we are inside the extension)
                            return ExtensionUtils.imports.ui[key];
                        else
                            return The store gnome shell version;
                    },
            }
        } catch (e) {
            global.log('Failed to add module in imports.ui:', key);
        } 
    }
```

But how to know the context?

**Comment by lestcape** [comment]
I don't know, because anyway currently the solution will be an string replace... So, it's broken anyway... If will be better than the currently and will work it's nice to me.

**Comment by jaszhix** [comment]
Ahh, I see. I like the idea of having both sets of modules available. I'm going to read more of the gnome modules source.

**Comment by jaszhix** [comment]
This is probably what we need: http://stackoverflow.com/questions/10093102/how-to-set-a-including-path-in-the-gjs-code

**Comment by lestcape** [comment]
I read that, and i think not, because only one file will be preserved. Here: it's the same problem and this is why i change the search path to the place where the uuid appear, because the uuid it's unique, and thats save the day, but it's wrong my code. In new versions of the shell, probably this can be done, but not now.

This comment it's not true, in my version, it returned the same global import:
https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/ui/extension.js#L162-L163

**Comment by jaszhix** [comment]
Ah ok. So I tried this:

```js
for (let key in ExtensionUtils.imports.ui) {
       try {
            Object.defineProperty(_importsUI, key, {
                get: function() {
                    if (getCurrentFile()[0].indexOf('/classicGnome@lestcape/') !== -1) {
                        return ExtensionUtils.imports.ui[key];
                    } else {
                        return imports.ui[key];
                    }
                }
            });
        } catch (e) {
            global.log('Failed to add module in imports.ui:', e);
        } 
    }
```
That function seems to return an array containing the string path of the file calling it. I think if we call it inside the getter, it might work.

But that code is not going to work because I'm still reassigning imports.ui below the for in loops.

**Comment by lestcape** [comment]
Yes, i think thats will work, just we need to do first:
imports.sui = imports.ui 

and then return imports.sui[key];

I think.

**Comment by jaszhix** [comment]
```imports``` is just a normal object I think, so its mutable. I found a standalone clone utility and cloned the ui object and I'm getting different errors now.

```sh
(gnome-shell:1846): Gjs-WARNING **: JS ERROR: Exception in callback for signal: extension-found: Error: No JS module 'nodeType' found in search path
clone@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/environment.js:62
init@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/environment.js:265
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/extension.js:10
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:167
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:297
_emit@resource:///org/gnome/gjs/modules/signals.js:124
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
init@resource:///org/gnome/shell/ui/extensionSystem.js:346
_initializeUI@resource:///org/gnome/shell/ui/main.js:209
start@resource:///org/gnome/shell/ui/main.js:120
@<main>:1
```

**Comment by lestcape** [comment]
I think it's because it's not if/else if not exist also we need to find if exist in the other domain.

**Comment by jaszhix** [comment]
The problem I'm running into is, checking for undefined or using hasOwnProperty triggers that "not found in search path" error. I'm not sure how to check the native imports object yet. And seems to be tripping up normal clone functions.

**Comment by jaszhix** [comment]
It looks like this now:

```js
StPatches.init();
    Overrides.init();

    function copy(o) {
        var _out, v, _key;
        _out = Array.isArray(o) ? [] : {};
        for (_key in o) {
            v = o[_key];
            _out[_key] = (typeof v === "object") ? copy(v) : v;
        }
        return _out;
    }

    let importsCache = copy(imports);
    let _importsUI = {};
    let _importsMisc = {};

    // Build the Cinnamon versions of imports.ui and imports.misc.
    /*for (let key in ExtensionUtils.imports.ui) {
       try {
            if (typeof _importsUI[key] === 'undefined') {
                _importsUI[key] = ExtensionUtils.imports.ui[key];
            }
        } catch (e) {
            global.log('Failed to add module in imports.ui:', key);
        } 
    }*/

    for (let key in ExtensionUtils.imports.ui) {
       try {
            Object.defineProperty(_importsUI, key, {
                get: function() {
                    if (getCurrentFile()[0].indexOf('/classicGnome@lestcape/') !== -1 || importsCache.ui[key] === undefined) {
                        return ExtensionUtils.imports.ui[key];
                    } else {
                        return importsCache.ui[key];
                    }
                }
            });
        } catch (e) {
            global.log('Failed to add module in imports.ui:', e);
        } 
    }
```
And I'm seeing this stack trace:

```sh
Gjs-Message: JS LOG: Failed to add module in imports.misc:, config

(gnome-shell:1846): Gjs-WARNING **: JS ERROR: Exception in callback for signal: extension-found: TypeError: ExtensionUtils is undefined
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/messageTray.js:23
init/<.get@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/environment.js:295
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/panel.js:26
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/extension.js:11
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:167
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:297
_emit@resource:///org/gnome/gjs/modules/signals.js:124
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
init@resource:///org/gnome/shell/ui/extensionSystem.js:346
_initializeUI@resource:///org/gnome/shell/ui/main.js:209
start@resource:///org/gnome/shell/ui/main.js:120
@<main>:1
```

**Comment by lestcape** [comment]
A clone at first level only need to work.

imports.sui= {};
for (let key in imports.ui) {
    imports.sui[key] = imports.ui;
}

There are only files in imports.ui

**Comment by lestcape** [comment]
The problem could be that i need to import Main from gnome shell, because i can not override ui.main, as have a lot of instances. I also don' t override config, but probably this last can be easy override. so if you try to find Main in a shell context this will fail. I need to sleep. Good night.

**Comment by jaszhix** [comment]
Ah, I see. Thanks for the input, and good job getting those other applets working! Night.

**Comment by jaszhix** [comment]
Removed all of that object mutating mess of code and simply assigned ExtensionUtils to ```window.cimports```, and applied the renaming scheme to all the applets. 

Applets working for me:
 * panel launcher
 * show desktop
 * trash
 * user
 * calendar
 * window quick list

**Comment by lestcape** [comment]
I think we can do more latter, but it's ok to me... You can merge the pull to the repository when you want. You understand perfectly the logic now, so if you have some problem ask me, if not, just merged it.

**Comment by jaszhix** [comment]
Ah, yeah agreed. I think this is at least a temporary solution. I just think calling that ExtentionUtils method everywhere is going to be hard to string replace. I'll be thinking about a better way to do it. Thanks for inviting me.

**Pull request merged**
