### PR TITLE
Fix improper Gio instance, fix main settings module

### PR DESCRIPTION
**Pull request by jaszhix**
Gio needs to be called with a new prefix and use the schema_id prop for
the overrides to take effect.

### CODE REVIEW

**Comment by lestcape** [comment]
I think this could work at the end of the function overrideGio : https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome@lestcape/ui/overrides.js#L104
```
Gio.Settings.new = function(schema_id) {
    return new Gio.Settings({ schema_id: schema_id });
}
```

**Comment by jaszhix** [comment]
That did the trick. Works for me.

**Comment by lestcape** [comment]
We have a problem with hot keys... Gnome required a Gio.Settings for keybindings and cinnamon not. If we want to add a keybinding dynamically, we need to generate an xml with a gsettings schema structure, then save it, then compiled it and then load it in a gio.settings, to then send the configuration to the shell...

Not nice...

**Comment by jaszhix** [comment]
Maybe we could integrate [this](https://github.com/rliang/gnome-shell-keybinder).

**Comment by lestcape** [comment]
Yes, this do exactly what i was thinking it's needed, but there are another way. Just that’s it's not documented an appear in only one place. 

https://github.com/GNOME/gnome-shell/blob/695bfb96160033be55cfb5ac41c121998f98c328/js/ui/shellDBus.js#L212-L229

See: https://bugzilla.gnome.org/show_bug.cgi?id=778809

**Comment by lestcape** [comment]
Probably we need the code of this extension to generate the default cinnamon keybinding and the another code to generate the specific keybinding of the extension on fly... I will working on it this weekend.

**Comment by lestcape** [comment]
@jaszhix Fork the gnomenu for Cinnamon probably it's not a good option... as this is in the roadmap of cinnamon

**Comment by jaszhix** [comment]
@lestcape Well, they can build their menu, and then we'll see if I want to keep using mine.

**Comment by jaszhix** [comment]
@lestcape I didn't use babel this time, so anybody can edit the code without messing with Node. No external libs are in use either, so it would be straight forward if they wanted to use parts of it, after formatting it for their style. Though Gnomenu is GPL3 - not sure how that works in a GPL2 project.

**Comment by lestcape** [comment]
I just read the roadmap, i don't know his real intension with that... I finished porting the indicator code of gnome shell, just because i use it to create a global menu. It's possible that they ask you if you can add the menu for cinnamon, if they are really interested.

**Comment by lestcape** [comment]
I will ending be more crazy that what i I'm.... I never understand how the key-binding of cinnamon works and i know now why this is so complex... They take it from gnome shell and in gnome shell this is a miss... I actually have the key-binding working, but i can not override his default key-binding yet in a good way... I think that i will finished adding all currently key-binding of gnome shell in a list, because i don't know how in a dynamic way i can know all key-bindings that are active.

**Comment by jaszhix** [comment]
Yeah, I actually tried to use that key binder I linked to a couple weeks ago to poor results. GNOME makes everyone use schemas, and Cinnamon provides a convenience layer around them - they might have done some of this in C, for all I know.

**Comment by lestcape** [comment]
Yes, but they have about 8 types of keybindings.... and in differents levels and differents shemas, some for mutter, others for the shell, others for gnome settings daemon.... jump   (-_-) ªªªª

**Comment by jaszhix** [comment]
@lestcape Well you were right, it seems like they're already looking for reasons not to publish it. I think if they don't I'm going to switch distros/DEs permanently. Just too much bureaucracy to keep up with.

**Comment by jaszhix** [comment]
@lestcape Is this PR okay? I can't test your new changes without re-adding these changes or I can't use the extension.

**Comment by lestcape** [comment]
Your old pr was long, and i was waiting for all this... But ok, just tell me, not problem... :)

**Comment by jaszhix** [comment]
Sorry about that - your solution was infinitely more elegant, I should have clarified.

**Comment by lestcape** [comment]
Not matter the elegance, it's just not need to replace a lot of things in the three party extensions or will ending doing a lot of unnecessary  things...

**Comment by lestcape** [comment]
Do you know where it's the declaration of the class GSettingsSwitch:
https://github.com/linuxmint/Cinnamon/search?p=2&q=GSettingsSwitch&utf8=%E2%9C%93

I can not find it.

**Comment by jaszhix** [comment]
Yeah, I don't see it either. Is it possible its being declared in another component Cinnamon uses, outside the repo?

**Comment by lestcape** [comment]
I don' t know but need to be.... This can not appear just because of magic...

**Comment by jaszhix** [comment]
Here you go https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/GSettingsWidgets.py#L311

**Comment by lestcape** [comment]
Yes i disable it, because This need a fix, we have not multiple inheritance in java script: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/GSettingsWidgets.py#L292

**Comment by jaszhix** [comment]
It looks similar to what you've already ported over, though at quick glance I'm not understanding all the context yet. https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/settings/jsonSettingsWidgets.js#L362

**Comment by lestcape** [comment]
Yes, but in that case i was have a lot of used case to test what this was doing... I need a lot of side page that use that, to have an idea of what this is doing... I have not idea right now and i working on port some side page that use that.

**Comment by lestcape** [comment]
I like the settings now. I'm happy... Test i and tell me what you think...
just execute cinnamon-settings in your terminal, not matter where you are or how call that and if he use spaw or the wrapper.

**Comment by jaszhix** [comment]
It seems to crash whenever I click any of the icons except applets because of schema errors.

```
Loading Accessibility module

(Classic Gnome:2293): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.desktop.interface' is not installed

Trace/breakpoint trap (core dumped)
```

The only setting I could access was Applets, is there a way to add the schema override to the settings?

**Comment by lestcape** [comment]
Yes, there are a lot of keybindings working not, because i enable the code of GsettingsWidgets. It's not necessary the override in The settings... All key-binding in the settings can be reallocate to the real schema without problem

**Pull request merged**
