### PR TITLE
Patch Util CLI utilities' parameters to call classic-gnome's settings

### PR DESCRIPTION
**Pull request by jaszhix**
This is in a global function so it can be reused in both
Util.spawnCommandLine and Util.trySpawnCommandLine.

### CODE REVIEW

**Comment by lestcape** [comment]
Yes, this is not optimal, but i have not anything better, will be merged.

**Comment by jaszhix** [comment]
Thanks. I got third party xlet download list checkboxes working, downloading is working, and the problem we're going to face is there not being an alternative to that zipfile python utility. I'm thinking maybe we can use spawn CLI method to extract the zips in the user install folder, then process them with Gio. What do you think?

**Comment by lestcape** [comment]
Yes, this is what we will do: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/tools/testerApp.js#L255-L273

This code come from here:  https://github.com/GNOME/gnome-shell/blob/695bfb96160033be55cfb5ac41c121998f98c328/js/ui/extensionDownloader.js#L70-L107

**Comment by jaszhix** [comment]
Ok, I'll try to use that.

**Comment by lestcape** [comment]
I think it's better use what gnome shell use, to not need any additional requirements, but if you find another way without need more things, thats also will be ok for me. There are a gi repository for zip, but i don't know if it's installed as default.. I think not.

**Comment by jaszhix** [comment]
Ah, ok. I cleaned up what I've added so far and got it working with that method you suggested. https://github.com/lestcape/Classic-Gnome/pull/12/commits/27e7c4212f144b7dc5380c97979c32a6fc843615

**Comment by lestcape** [comment]
Yes, but we need to download and extracted it in a temporal directory, and only move it to the right place when we finished all task... this is how this work on cinnamon, and i think it's the best, we don't know what could happen, and if somethings wrong happen, it's better that the system clean the miss in a temporal dir than us.

**Comment by jaszhix** [comment]
I didn't change any of the directory paths, I just made sure it is extracting to the classic-gnome directory in .local/share.

**Comment by lestcape** [comment]
Yes, that it's what i say, don't extracted it in our directory, made the extraction outside in the temp folder, do all thing there and then move the result to the directory.

**Comment by jaszhix** [comment]
Sorry, misread your message. I can do that.

**Comment by lestcape** [comment]
The problem it's that cinnamon can read what it's inside the zip, we can not. So, we need to ensure this is a well former extension outside our place, also we will apply a patch there, if all was ok and only in this case, we can move the extension to our place.

**Comment by lestcape** [comment]
What i will do then? :) We will move the main side page of the cinnamon settings or we will implemented another? I think i will work to move the panel side page. We have not a way to configured the panel yet.

**Comment by jaszhix** [comment]
Yeah, that sounds like a good idea. I guess it depends on what's easiest for you - porting more python, or writing one from scratch. The benefits of the latter would be we could integrate it into the gnome extension settings, maybe.

**Comment by lestcape** [comment]
Yes, this is exactly why i don't know what will be the best with the main side page. I can not decide it, i don't know if finally we can integrate it or not... I think we need to move the main side page, and later try to find a way to integrate it, because at less i can not ensure we can integrate it properly.

**Comment by jaszhix** [comment]
Ah, yeah. I think this extension is doing a lot and providing a lot of extra UIs as it is. At least in the short term, we can try to get the extension feature complete in the most practical way, and then after its stable, start refining.

**Pull request merged**
