### PR TITLE
Add org.classic.gnome.settings-daemon schemas, string replace all…

### PR DESCRIPTION
**Pull request by jaszhix**
…files, and add remaining default applets. I was able to run the extension with all cinnamon schemas uninstalled with these changes.

The settings changes not taking effect with applets was also resolved for me after I removed multiple dud JSON files in ~/.classic-gnome/configs. Panel settings don't work for me yet, but could be a similar issue. I.e, it assuming multiple panels are installed and never configuring the right one.

### CODE REVIEW

**Comment by lestcape** [comment]
The settings run as a different application in a different environment where i don' t apply a path to gio settings, but for classes inside cinnamon i apply a patch to gio (ui and misc...), if you change that files (the files in ui and misc...), we have not a way to detected problems... If there are problems need to be resolved by us, and not with a replace.

**Comment by jaszhix** [comment]
I made sure not to change overrides in ui/overrides.js, what file in misc did I miss?

**Comment by lestcape** [comment]
@jaszhix the idea it' s add more things in override:
https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/ui/overrides.js#L11-L50

It' s there where i make the replace, if you change things for individual files, this will only will work for our files and not for external applets...

**Comment by lestcape** [comment]
This is working not for the last change, it' s working because of the first change. The schemas are not localized by the file name, are localized by the internal id. The file name are not used by Gio and could be any and not matter.

Cinnamon have a schema and gnome have another, you can not assign a cinnamon schema to a gnome one, because they not need to share the same properties... You only can assign a cinnamon schema to a clone of this schema with a different id, but of course the clone schema are not read by the original program. In this case the setting-daemon. So, you need to bind all properties one by one to the equivalent property that it' s reading by the setting-daemon.

**Comment by lestcape** [comment]
The bind need to be in a bidirectional way.

**Comment by lestcape** [comment]
In other words: how cinnamon it's a fork of gnome this work, because in the cinnamon side they don't change the properties name just the id, but what happen when an applet call the a pure cinnamon property? just will crash because that property don't exist in the gnome schema. If you have a clone it's a warranty that the property exist, and then this will not crash, but it's not all that it's needed because you can not see the effect, as there are not a bind to the real property.

**Comment by lestcape** [comment]
I don' t do any bind yet... Just i clone some schemas and redirect the creation of a cinnamon schema to our copy, just to not crash.

**Comment by jaszhix** [comment]
Ah ok. Yeah, I didn't mean to include the file names in those items in the last commit.

**Comment by lestcape** [comment]
Just one thing, revert the internal file change, that the only way to know that this is working.

**Comment by jaszhix** [comment]
File change? Can you link me to the file that needs to be reverted?

**Comment by lestcape** [comment]
For example this line: https://github.com/lestcape/Classic-Gnome/pull/15/files#diff-add575ed92677d0ddf3f21010082e391R30

**Comment by lestcape** [comment]
It's practically all files, except the gsettings schemas the override file and the new applets that you added if they don't used our gschemas.

**Comment by jaszhix** [comment]
So revert all the string replacement? That's what got the extension not crashing for me - I uninstalled all the Cinnamon schemas. I think it would be better to just change out the schemas when we string replace xlets, I started that a little bit [here](https://github.com/lestcape/Classic-Gnome/pull/15/files#diff-14792a96c3a9fc65fff16ca95a8ce9caL30), and maintain our own namespacing in our own files. Its just more confusing to me seeing cinnamon schemas in our code.

**Comment by lestcape** [comment]
Not, i don't say remove the replace i say you are doing the replace where it's not the place if you make the replace in a good way in override, the extension will not crash.

**Comment by lestcape** [comment]
Thats not need to be added as a replace, because is added in override.

**Comment by jaszhix** [comment]
The overrides.js doesn't work in the settings sidepages because they have their own globals. I don't know how to determine what you think needs replaced and what doesn't. I'm approaching this the way I think is cleaner. If you're worried, pull my fork, check out the branch, delete your Cinnamon schemas and test it.

**Comment by lestcape** [comment]
True, the classes that we uses in the settings have not a patch, but you are not replacing any class that are used in the settings. Not one trhid-party extension will use directly the settings class because this classes don't exist in cinnamon in js, so in the settings class we can do what we want.

**Comment by lestcape** [comment]
Yes, i can make the change, of thats things, but will not be now, if you have not inconvenient with wait a little for me.

**Comment by jaszhix** [comment]
My understanding is the settings daemon schemas are useless - but if so, does it matter what they're called? They're still mirroring cinnamon. I could revert those back to org.cinnamon.settings-daemon. Or Revert all the files overrides.js will work on?

**Comment by lestcape** [comment]
Not will not work... Just simple will not crash. To work, we need to do more things. the problem it's that i have cinnamon installed, so it's more difficult to me note a problem, but i do that with others and it's working. Also i generate a list of the things that i changed here: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/schemas/schema.changes

Another problem it's that the schema file don't need to have one id, thay can have more than one. So remove the last part, it's not the idea... We need to open the schema localized the real id (all ids) and add it to the list.

**Comment by lestcape** [comment]
And yes it's a big work, tired and annoying

**Comment by lestcape** [comment]
Also the enums ids need to be changed, not just the schema ids.

**Comment by lestcape** [comment]
Another thing, i have not a fix to all replace that we are doing in the settings when we install an xlet, but if i have an internal fix, not matter if it's complex to implement or not, i prefer implement a solution (a hack) that override an string in the installation. My idea it's not need to replace anything, but probably this will not be possible, and actually i don't know ho if will be or not.

**Comment by jaszhix** [comment]
> Another problem it's that the schema file don't need to have one id, thay can have more than one. So remove the last part, it's not the idea...

Which last part?

I agree, it'd be better to create a fully compatible API environment than string replace. It works though, and saves time for now.

**Comment by lestcape** [comment]
This last part: .gschema.xml

Yes, and not, because they way that i have to know what it's needed it's when something crash fix it... You have another way to detect that something it's wrong?

If i fix it in a non good way, just i will not see the crash and i will not try to fix it.

**Comment by lestcape** [comment]
In other words how i know that in override there are not a missing schema replace? I will not open all schema one by one several times to see if i can detected what it's missing.... The crash will help me to know what it's missing.

**Comment by jaszhix** [comment]
I think it only crashes if the main schemas aren't in place, like org.classic.gnome. I think I removed the gschema part, are you referring to [this](https://github.com/lestcape/Classic-Gnome/pull/15/commits/100aad153d2550881c57f0ae48bb92327fc526aa)?

There's probably a way to unit test it.

**Comment by lestcape** [comment]
Yes i refereed to this: https://github.com/lestcape/Classic-Gnome/pull/15/commits/100aad153d2550881c57f0ae48bb92327fc526aa

Yes there are ways to test things, but also will required more work and more time...

**Comment by jaszhix** [comment]
@lestcape So I think that covers what you wanted?

**Comment by lestcape** [comment]
what i want???

**Comment by jaszhix** [comment]
@lestcape Sorry, I'm not following. I removed the part you asked me to remove before you told me to remove it.

**Comment by lestcape** [comment]
What i say was, that what we need are the id of the properties, not the file name. Remove that part it's not solve the problem. Solve the problem it's add the id's and not the file name or the file name without that parts also it's not solved the problem.

What i say it's that probably this won't work for you, because you are not adding all id's and what i say it's that this will work if all id's are adding propertly.

**Comment by lestcape** [comment]
Another thing that i say it's that we can not have a way to know if really it's working properly if we don't revert all string replace that you add inside the ui and misc files.

**Comment by lestcape** [comment]
How i know that you only remove that part without test anything and open any file? just easy. The enum can not be in that way... This id just not exist: https://github.com/lestcape/Classic-Gnome/pull/15/commits/100aad153d2550881c57f0ae48bb92327fc526aa#diff-bdab761f860ecfe0318e678d6c41fdb6R50

**Comment by jaszhix** [comment]
No, I did test it. I don't see what point you're trying to make by saying that. I'll fix it tomorrow, I'm still doing client work and exhausted.

**Comment by lestcape** [comment]
The point it's that you can test it, but really you are not test it, because nothing it's really replaced, because you do the replace directly in the code, so nothing math inside override and that part can not be tested.

**Comment by jaszhix** [comment]
Yeah, I understand now what you're saying. I didn't really understand how the overrides worked, and I wasn't basing my changes off any deeper understanding of the schemas itself, but trial and error trying to get a vanilla Gnome Shell working. Some of the changes might have been too cautionary, so I'll go back and see how much I can revert before it crashes again.

**Comment by lestcape** [comment]
Yes but also see, you are replacing also Dbus in the screen saver, this have nothing to be with gsettings schemas. : ) The idea of the override it's exactly what you are doing in the code, replace the schema ids and then construct the Gio.Settings... Just the replace occurs in the constructor of the object and then you don't need to replace anything in the code.

**Comment by jaszhix** [comment]
Ok, I reverted, and its crashing on a lot of missing schemas in ui/misc. 
I also reverted overrides.js to how it was before this PR. I forgot to mention I didn't fully uninstall Cinnamon schemas myself until testing this PR.

screenshot from 2017-02-15 22-07-47

**Comment by lestcape** [comment]
Yes that mean that the override.js is not working, just i don't know the reason of course. This need log to see, if this call enter in the constructor and if it's translated to our id or not: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/ui/overrides.js#L65

**Comment by lestcape** [comment]
Cloud be that we have things that are called first that the override call...

**Comment by jaszhix** [comment]
Is that the gettext-domain?

**Comment by lestcape** [comment]
Ahhh... You also revert the patch... Ofcourse this can not work.

**Comment by jaszhix** [comment]
Ok. At this point, it might be easier to just delete this branch and retry.

**Comment by lestcape** [comment]
Yes i thing will be more easy, create a new brash, but not remove this one, can help us to know all necessary changes.

**Comment by jaszhix** [comment]
By the way, with the current state, its working for me with just our schemas installed. But not through overrides which I guess would make it easier to track upstream (Cinnamon) changes when diffing.

**Comment by jaszhix** [comment]
I get the same core dump event switching to the master branch @ 40cf52a29949a6088fdba5dd675f1b3bc390d0b6.

**Comment by jaszhix** [comment]
https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/ui/keybindings.js#L25 - I wonder if its the way Gio is getting called? I.e, no new constructor prefix.

**Comment by jaszhix** [comment]
That was it! PR incoming...

**Comment by lestcape** [comment]
Yes,  only hack the normal constructor. not Gio.Settings.new, there are a lot of ways to construct a gio.settings.... I think will be nice add a hack to this way also, but it's less commons.

**Pull request closed without merging**
