### PR TITLE
Patch global.create_app_launch_context, ClassicGnome.IconChooser, indicate Fedora 25 compatibility

### PR DESCRIPTION
**Pull request by jaszhix**
* Patched global.create_app_launch_context, which gets recent document menu items working in the recent and menu applets.
* Patched ClassicGnome.IconChooser, this fixes the icon selector in the menu applet.
* Updated COMPATIBILITY.md.
* Indicated Fedora 25 compatibility.

### CODE REVIEW

**Comment by jaszhix** [comment]
That doesn't work, I tried it. The function reference is the same and it causes endless recursion and crashes Gnome. If you find your way works, I'm all for it. I figured since we settled on string replacing xlets it didn't matter.

**Comment by lestcape** [comment]
I can merged it then?

**Comment by jaszhix** [comment]
Yeah, feel free anytime I open a PR. :) Unless I add [wip] to the title.

**Comment by lestcape** [comment]
I don't see a recursive problem... I just do it a lot of times here... You apparently don't save a copy of the original function and don't use it instead of the original one. This is important to avoid the recursion...
https://github.com/lestcape/Classic-Gnome/commit/11eaccfb019f4a0efc73d6bdbb82b9df35d6ffd9

**Comment by jaszhix** [comment]
Ahh, I see. I think I tried to assign the function to the fake property, and called the original inside that - reverse of what you did. Glad that worked, its a better solution. I think I get tripped up on GObjects having their own unique features compared to JS objects, and assume some of the native objects can't be immutable.

**Comment by lestcape** [comment]
Yes, but we can not do the same always : ( Some special functions are protected, like spaw because obliviously reason (the security)... If you try to do that with Glib.spaw, when you try to call the function, this function return null, and don't let you override it... At less i can not do it yet... We need that for the settings as we speak...

**Comment by jaszhix** [comment]
By the way, I am able to use the extension without Cinnamon now. Just need to ensure the schemas are still in ```/usr/share/glib-2.0/schemas/```, and run ```glib-compile-schemas /usr/share/glib-2.0/schemas/```. As a test, I replaced the applet configure menu option with classic gnome's xlet-settings.js, and its starting to feel more independent.

**Comment by lestcape** [comment]
Yes that the finally idea.

I have a problem with the settings to load the applets (i fix it in my code), they appear more than one time I don't know yet how resolve it.

**Comment by jaszhix** [comment]
You mean when running ```xlet-settings.js applets```? Yeah, I noticed it can't see what's installed/enabled.

When I try to add an applet:

```sh
(Gnocine:3970): GLib-GIO-ERROR **: Settings schema 'org.cinnamon' does not contain a key named 'name'
```

Installing a third party applet:

```sh
(Gnocine:3970): Gjs-WARNING **: JS ERROR: Error: Expected type struct for Argument 'path' but got type 'string'
ExtensionSidePage<.gm_toggled@/home/jason/.local/share/gnome-shell/extensions/gnocine@json/settings/extensionCore.js:1061
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
Application<.run@./xlet-settings.js:127
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
@./xlet-settings.js:433
```

I have been tempted to look in spices.js, but there's plenty of broken things to fix everywhere.

**Comment by lestcape** [comment]
The problem it's that: The schema's can not be called with the same name than on cinnamon, because this will cause a conflict with cinnamon. We need to rename the schema files name and also the internal name (**the id and path of the schema**) https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/schemas/org.cinnamon.desktop.a11y.applications.gschema.xml#L3.

The schema file name it's not a problem, but change the internal id and path cause that you need to change it in all places where a Gio.schema is constructed. We need then a hack of the construction of the schema, because we need to redirect the construction to another id (our id)...

Thats will be all to run the extension outside cinnamon scope.

You can construct the schema, because the cinnamon schema definition are wrong, they don't know that, but the specification of a schema changed, and you also need to declared your enumerations:
This is not added to the cinnamon schema specification, example:
https://github.com/lestcape/Classic-Gnome/blob/a1ba0466a3b3ecb9ae7405f048630d3c9d80dfec/classicGnome%40lestcape/schemas/org.cinnamon.desktop.a11y.mouse.gschema.xml#L3-L8

**Comment by lestcape** [comment]
I try to say: You could not build the schemas before, because the enum problem.

About the error that you notice i fixed it in my code.

**Comment by jaszhix** [comment]
Ah, that makes sense. This [script](https://github.com/jaszhix/Gnocine/blob/master/installSchemas.sh) is what I made to get it working, I had to delete the enumerations.

**Comment by lestcape** [comment]
Not, you can not need to delete it, when we rename it.

**Comment by jaszhix** [comment]
I don't have much experience messing with gsettings schemas, is it as simple as applying renames, or I'm guessing the format of the XML?

**Comment by lestcape** [comment]
Ok, if it's important to you that we can use it without cinnamon, i will do that now... Anyway this need to be done.

**Comment by lestcape** [comment]
I will add a file to specify all name changes that we will do.

**Comment by jaszhix** [comment]
> About the error that you notice i fixed it in my code.

How come its not committed?

**Comment by lestcape** [comment]
I speak about it: https://github.com/lestcape/Classic-Gnome/pull/10#issuecomment-279123050

**Pull request merged**
