### PR TITLE
Implement xlet downloading, sort dropdown, xlet running icons, configure button, remove from panel button, right click menu

### PR DESCRIPTION
**Pull request by jaszhix**
Xlet settings overhaul.

### CODE REVIEW

**Comment by lestcape** [comment]
They are constants and they are declared global (just remove the this): https://github.com/lestcape/Classic-Gnome/pull/12/files/5b65b7978f6a1b6d03bb76a2cc46b68986eb5c23..b331057577bd8671f46729016a06003be5e4e717#diff-3620c82ac661c7a55067325111cbd3bbL1133

Or will be difficult, to know what the value mean.

**Comment by jaszhix** [comment]
Ok, that's fixed. There's a lot of bug fixes in this PR. You can merge it if you want, I'll just open another and keep working off this branch.

**Comment by jaszhix** [comment]
I'm able to add third party applets now, and all the ones I'm testing are working! But still need to figure out how to change the model value in extensionCore from spices.js so it adds to the installed list. Currently have to restart Shell.

**Comment by lestcape** [comment]
I think, it's just that the Dbus proxy won't work ok, not the model...

**Comment by jaszhix** [comment]
Ah, ok. I can probably find a way to trigger a callback or emit a signal for now. And spoke too soon, forgot to patch ```imports.gi.Cinnamon```.

**Comment by lestcape** [comment]
Can you move the replace string to the top of the file as const, **replacementStrings**, just to be more easy for us add more things, when needed...

I will looking about moverecursive, copyrecursive and deleterecursive

**Comment by lestcape** [comment]
Do you know if exist a replace to the PIL package from javascript: https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/bin/imtools.py#L21

**Comment by jaszhix** [comment]
Yeah, there's some replacements, but chances are we would have to modify it for GJS. You might want to look at [npmjs](https://npmjs.com). Anything using canvas or browser features is a non-starter. I think there are a few pure-JS image libs. I can look around.

**Comment by lestcape** [comment]
This is the only lib in the settings, that we can not easy move to gjs. I will look also for this...

**Comment by jaszhix** [comment]
I'm guessing this is for wallpapers? Would it make sense to try to execute some python dependencies directly, maybe modify them to accept argv and store the image somewhere that the JS can pick up?

Here's an [example lib](https://github.com/oliver-moran/jimp), but its really reliant on node.

**Comment by lestcape** [comment]
I don't know in all places that this is used. I think could be better see exactly the usage case and just port the things that we need in any case... Or implemented it.... I have a color chooser that works with pixels, maybe will be something easy.

**Comment by jaszhix** [comment]
I need to sleep. Feel free to merge it in or leave notes, I'll look at it "tomorrow".

**Pull request merged**
