### PR TITLE
Add global.loadCinnamon method

### PR DESCRIPTION
**Pull request by jaszhix**
This moves the try-catch block for importing Shell/Cinnamon in every
file to one place, so it'll be easier to experiment with gi.

### CODE REVIEW

**Comment by lestcape** [comment]
We don't need to do that here, as we are inside Gnome shell, thats object are private, but it's private for  us:
https://github.com/lestcape/Classic-Gnome/pull/3/files#diff-ceda1744a85093ea5fcebacd7c94971fR68

Cinnamon do the same with the equivalent typelibs, they are private for cinnamon, so this is why we can not access to imports.gi.Cinnamon if they was public we can access this objects because Cinnamon it' s installed. 
Read this if you can, this can give you a good idea about typelibs: http://mathematicalcoffee.blogspot.mx/2012/09/developing-gnome-shell-extensions_6.html?m=1

There are something different from calendar? https://github.com/lestcape/Classic-Gnome/pull/3/files#diff-2c77c4494457102f84c1aa98e8c11d72R8

**Comment by jaszhix** [comment]
Ah ok, so yeah we can't access gi.CInnamon anyway.

Yeah the CinnamonDesktop import was in the try-catch block, but I left it as-is since its only in the one file. We could possibly add another method to load it later if you think it'll be reused like that a lot. I'm trying to minimize the extra boilerplate needed for extensions. I probably should've just moved the try-catch block as it was to a method for this commit.

Should we just import Cinnamon using ```imports.gi.Shell``` for now then?

**Comment by lestcape** [comment]
What actually we can do with trhid-party extension it' s read all js code and make a recursive replace of the imports string. It's more easy if the replace will be the same in all cases. 

Yes, we can use imports.gi.Shell, this is only there because i have the idea of test the final code in cinnamon, so in that way we can be sure that we don't break the cinnamon api.

**Comment by jaszhix** [comment]
Ah ok. I went ahead and added some patches to Main, expo and the logging methods.

**Comment by lestcape** [comment]
I'm actually forking the Main class to have our own instance, without break anything of Gnome shell. The idea will be move the code one by one to that place when ready and remove the Gnome shell implementation that we override.

**Comment by jaszhix** [comment]
That's probably better then. Are you forking Gnome's version of Main? I think one benefit to patching Main is less breakage to deal with on newer versions of Gnome Shell.

**Comment by lestcape** [comment]
I'm trying to fork the Gnome shell version, but finally we don't need this. It's just for have things working while we finished the migration of all things... actually we can remove the Shell functions of Main.

**Comment by jaszhix** [comment]
Ok, I'll leave you to it then. Let me know when you think you're at a place you need help.

**Comment by lestcape** [comment]
@jaszhix :) jajajaja.... Sorry... What i try to say it's: 
1- We actually need the shell function of Main.
2- When we finished the migration, we don't need shell function of Main.

Thats have nothing to be with your pull that it's ok in my opinion.

**Comment by jaszhix** [comment]
Ahh ok lol, I wasn't sure, so should I reopen and merge?

**Comment by lestcape** [comment]
I have that: 

```
const Clutter = imports.gi.Clutter;
const Gdk = imports.gi.Gdk;
const Gio = imports.gi.Gio;
const GLib = imports.gi.GLib;
const Gtk = imports.gi.Gtk;
const Lang = imports.lang;
const Mainloop = imports.mainloop;
const Meta = imports.gi.Meta;
const Shell = imports.gi.Shell;
const St = imports.gi.St;

const Main = imports.ui.Main;
const Main = imports.ui.Main;
const AccessDialog = imports.ui.accessDialog;
const AudioDeviceSelection = imports.ui.audioDeviceSelection;
const Components = imports.ui.components;
const CtrlAltTab = imports.ui.ctrlAltTab;
const EndSessionDialog = imports.ui.endSessionDialog;
const Environment = imports.ui.environment;
const ExtensionSystem = imports.ui.extensionSystem;
const ExtensionDownloader = imports.ui.extensionDownloader;
const Keyboard = imports.ui.keyboard;
const LegacyTray = imports.ui.legacyTray;
const MessageTray = imports.ui.messageTray;
const ModalDialog = imports.ui.modalDialog;
const OsdWindow = imports.ui.osdWindow;
const OsdMonitorLabeler = imports.ui.osdMonitorLabeler;
const Overview = imports.ui.overview;
const PadOsd = imports.ui.padOsd;
const Panel = imports.ui.panel;
const Params = imports.misc.params;
const RunDialog = imports.ui.runDialog;
const Layout = imports.ui.layout;
const LoginManager = imports.misc.loginManager;
const LookingGlass = imports.ui.lookingGlass;
const NotificationDaemon = imports.ui.notificationDaemon;
const WindowAttentionHandler = imports.ui.windowAttentionHandler;
const Screencast = imports.ui.screencast;
const ScreenShield = imports.ui.screenShield;
const Scripting = imports.ui.scripting;
const SessionMode = imports.ui.sessionMode;
const ShellDBus = imports.ui.shellDBus;
const ShellMountOperation = imports.ui.shellMountOperation;
const WindowManager = imports.ui.windowManager;
const Magnifier = imports.ui.magnifier;
const XdndHandler = imports.ui.xdndHandler;
const Util = imports.misc.util;


const A11Y_SCHEMA = Main.A11Y_SCHEMA;
const STICKY_KEYS_ENABLE = Main.STICKY_KEYS_ENABLE;
const GNOMESHELL_STARTED_MESSAGE_ID = Main.GNOMESHELL_STARTED_MESSAGE_ID;

let componentManager = Main.componentManager;
let panel = Main.panel;
let overview = Main.overview;
let runDialog = Main.runDialog;
let lookingGlass = Main.lookingGlass;
let wm = Main.wm;
let legacyTray = Main.legacyTray;
let messageTray = Main.messageTray;
let screenShield = Main.screenShield;
let notificationDaemon = Main.notificationDaemon;
let windowAttentionHandler = Main.windowAttentionHandler;
let ctrlAltTabManager = Main.ctrlAltTabManager;
let padOsdService = Main.padOsdService;
let osdWindowManager = Main.osdWindowManager;
let osdMonitorLabeler = Main.osdMonitorLabeler;
let sessionMode = Main.sessionMode;
let shellAccessDialogDBusService = Main.shellAccessDialogDBusService;
let shellAudioSelectionDBusService = Main.shellAudioSelectionDBusService;
let shellDBusService = Main.shellDBusService;
let shellMountOpDBusService = Main.shellMountOpDBusService;
let screenSaverDBus = Main.screenSaverDBus;
let screencastService = Main.screencastService;
let modalCount = Main.modalCount;
let actionMode = Main.actionMode;
let modalActorFocusStack = Main.modalActorFocusStack;
let uiGroup = Main.uiGroup;
let magnifier = Main.magnifier;
let xdndHandler = Main.xdndHandler;
let keyboard = Main.keyboard;
let layoutManager = Main.layoutManager;
let _startDate = Main._startDate;
let _defaultCssStylesheet = Main._defaultCssStylesheet;
let _cssStylesheet = Main._cssStylesheet;
let _a11ySettings = Main._a11ySettings;
let _themeResource = Main._themeResource;

 
function _sessionUpdated() {
    if(Main._sessionUpdated)
        Main._sessionUpdated();
}

//It's better do not add this function:
//function start() {}

function _initializeUI() {
    if(Main._initializeUI)
        Main._initializeUI();
}

function _getStylesheet(name) {
    if(Main._getStylesheet)
        return Main._getStylesheet();
    return null;
}

function _getDefaultStylesheet() {
    if(Main._getDefaultStylesheet)
        return Main._getDefaultStylesheet();
    return stylesheet;
}

function _loadDefaultStylesheet() {
    if(Main._loadDefaultStylesheet)
        Main._loadDefaultStylesheet();
}

function getThemeStylesheet() {
    return Main._cssStylesheet;
}

function setThemeStylesheet(cssStylesheet) {
    if(Main.setThemeStylesheet)
        Main.setThemeStylesheet(cssStylesheet);
}

function reloadThemeResource() {
    if(Main.reloadThemeResource)
        Main.reloadThemeResource();
}

function loadTheme() {
    if(Main.loadTheme)
        Main.loadTheme();
}

function notify(msg, details) {
    if(Main.notify)
        Main.notify(msg, details);
}

function notifyError(msg, details) {
    if(Main.notifyError)
        Main.notifyError(msg, details);
}

function _findModal(actor) {
    if(Main._findModal)
        return Main._findModal(actor);
    return -1;
}

function pushModal(actor, params) {
    if(Main.pushModal)
        return Main.pushModal(actor, params);
    return true;
}

function popModal(actor, timestamp) {
    if(Main.popModal)
        Main.popModal(actor, timestamp);
}

function createLookingGlass() {
    if(Main.createLookingGlass)
        Main.createLookingGlass();
    return null;
}

function openRunDialog() {
    if(Main.openRunDialog)
        Main.openRunDialog();
}

function activateWindow(window, time, workspaceNum) {
    if(Main.activateWindow)
        Main.activateWindow(window, time, workspaceNum);
}

// TODO - replace this timeout with some system to guess when the user might
// be e.g. just reading the screen and not likely to interact.
const DEFERRED_TIMEOUT_SECONDS = Main.DEFERRED_TIMEOUT_SECONDS;
var _deferredWorkData = Main._deferredWorkData;
// Work scheduled for some point in the future
var _deferredWorkQueue = Main._deferredWorkQueue;
// Work we need to process before the next redraw
var _beforeRedrawQueue = Main._beforeRedrawQueue ;
// Counter to assign work ids
var _deferredWorkSequence = Main._deferredWorkSequence;
var _deferredTimeoutId = Main._deferredTimeoutId;

function _runDeferredWork(workId) {
    if(Main._runDeferredWork)
        Main._runDeferredWork(workId);
}

function _runAllDeferredWork() {
    if(Main._runAllDeferredWork)
        Main._runAllDeferredWork();
}

function _runBeforeRedrawQueue() {
    if(Main._runBeforeRedrawQueue)
        Main._runBeforeRedrawQueue();
}

function _queueBeforeRedraw(workId) {
    if(Main._queueBeforeRedraw)
        Main._queueBeforeRedraw(workId);
}

function initializeDeferredWork(actor, callback, props) {
    if(Main.initializeDeferredWork)
        return Main.initializeDeferredWork(actor, callback, props);
    return null;
}

function queueDeferredWork(workId) {
    if(Main.queueDeferredWork)
        return Main.queueDeferredWork(workId);
    return null;
}

//Thats is a class:
const RestartMessage = Main.RestartMessage

function showRestartMessage(message) {
    if(Main.showRestartMessage)
        Main.showRestartMessage(message);
}*
```

**Comment by lestcape** [comment]
But if i try to import something from the shell ui inside the Main i can not.

**Comment by jaszhix** [comment]
Ah weird. Where is that file being imported from?

**Comment by lestcape** [comment]
This is in ui a main.js file. Try to import it using your method. cimports

**Comment by lestcape** [comment]
Also directly from the extension won't work...

**Comment by jaszhix** [comment]
I'll test it.

**Comment by jaszhix** [comment]
Yeah, I tried it in the panel-launcher applet and saw this:

```js
Gjs-Message: JS LOG: Loaded applet show-desktop@cinnamon.org in 13 ms
Gjs-Message: JS LOG: @/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/applets/panel-launchers@cinnamon.org/applet.js:9
Extension.prototype._init@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/extension.js:168
Extension@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/extension.js:122
loadExtension@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/extension.js:460
init@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/appletManager.js:47
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/extension.js:36
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:167
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:297
_emit@resource:///org/gnome/gjs/modules/signals.js:124
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
init@resource:///org/gnome/shell/ui/extensionSystem.js:346
_initializeUI@resource:///org/gnome/shell/ui/main.js:209
start@resource:///org/gnome/shell/ui/main.js:120
@<main>:1
```

**Comment by lestcape** [comment]
It's whatever we try to import from the shell... not the line ```const Main = imports.ui.Main;```

**Comment by jaszhix** [comment]
I see. Should I keep adding to mainPatches.js?

**Comment by lestcape** [comment]
Yes, of course all that you can...

**Comment by jaszhix** [comment]
Cool, just didn't want to work on the same thing you are, I thought that was the case earlier heh. By the way, I usually have to comment out the try-catch in the root extension.js file or I don't see any stack traces - is that what you do?

**Comment by jaszhix** [comment]
I'm trying to add ui/overview to mainPatches, and I see this:

```js
(gnome-shell:1772): Gjs-WARNING **: JS ERROR: Exception in callback for signal: extension-found: TypeError: global.overlay_group is undefined
Overview.prototype._init@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/overview.js:46
Overview@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/overview.js:27
patchOverview@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/mainPatches.js:192
init@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/mainPatches.js:21
init@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/ui/environment.js:212
@/home/jason/.local/share/gnome-shell/extensions/classicGnome@lestcape/extension.js:10
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:167
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:297
_emit@resource:///org/gnome/gjs/modules/signals.js:124
ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:174
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
bind/<@resource:///org/gnome/gjs/modules/lang.js:95
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27
ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:179
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:299
enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:307
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:338
init@resource:///org/gnome/shell/ui/extensionSystem.js:346
_initializeUI@resource:///org/gnome/shell/ui/main.js:209
start@resource:///org/gnome/shell/ui/main.js:120
@<main>:1
```

And I don't see global.overlay_group assigned anywhere in the Cinnamon code - so I'm wondering if this is a hard coded actor in cjs/Cinnamon?

**Comment by lestcape** [comment]
I don't understand where is not the try catch?

There are some things that are similar in gnome shell and in cinnamon, this type of thing can not be implemented directly, because we will have a conflict. applet are not in gnome shell or desklets and can be easy implemented.

My idea was use the shell code to implemented this features but keep the cinnamon iface...

**Comment by jaszhix** [comment]
I was talking about this: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/extension.js#L8

Yeah, it looks like from my brief googling Gnome deprecated it in 2013.

**Comment by lestcape** [comment]
The try catch it's not needed, this was for testing it.

Well, not idea why this happen with the overview then...

**Comment by jaszhix** [comment]
I figured it out, new [PR](https://github.com/lestcape/Classic-Gnome/pull/4).

**Comment by lestcape** [comment]
Good!!

**Comment by lestcape** [comment]
I think all my problems with Main are because of this... https://blogs.gnome.org/mclasen/2014/03/24/keeping-gnome-shell-approachable/

**Comment by jaszhix** [comment]
Yeah looks likely. I wonder if there's a workaround for this.

**Pull request merged**
