### PR TITLE
Fix ComboBox, initial state setting of spin buttons, and move the initial state…

### PR DESCRIPTION
**Pull request by jaszhix**
… setting to each class's _init instead of an else-if chain in jsonSettingsWidget

Spinbuttons were empty after this change: https://github.com/lestcape/Classic-Gnome/commit/0c9d73804ce41863b4c56665cd0e146cae4678c1#diff-ecea8de8764e0053cee79745be59d3f5L751

### CODE REVIEW

**Comment by lestcape** [comment]
I think, this is not the idea... Like you tell me you are fixed the combo box, i begin to work on the fix of the key-bindings. I fix it, but in the way, i can tell you something there are 2 things to fix:
- The widgets that works wit on_setting_changed : https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/settings/jsonSettingsWidgets.js#L334
- The widgets that work with this.settings.bind: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/settings/jsonSettingsWidgets.js#L330

Additional, there are some other specific behavior like this: https://github.com/lestcape/Classic-Gnome/blob/master/classicGnome%40lestcape/settings/jsonSettingsWidgets.js#L322

Like i say i have working the first and i'm working in the this.settings.bind without successfully yet.

**Comment by jaszhix** [comment]
Really? The settings are updating the applets for me. I just know that we're not calling set_value after we create the SpinButton object - so there's no way for it to.

I got stuck on the combobox and didn't make much progress there.

I'm looking at the search issue you mentioned in extensionCore, and I logged all the methods in the callstack and the ```query``` string variable in ```only_active``` has a length of 0 at all times. Not sure what's causing it yet. Still trying to absorb this code.

**Comment by lestcape** [comment]
@jaszhix yes, in the place where you make a lot of comments this occurs and it's ok, the problem it's later, to display the current value :) It's not so much your code, let me try to fix this, if i can not, we can go back to patch widget one by one.

**Comment by jaszhix** [comment]
Ahh, I didn't realize there was a proper for it to update those. Ok, that's cool.

**Comment by lestcape** [comment]
Yes it's like you say. This will be another surrender, this functions are implemented in a different way in python and in javascript, they received different parameter or also are a warper inside GObject.Object and not directly in GObject:  
- get_property
- set_property
- freeze_notify
- freeze_child_notify

Scolling use that for update properties on the Gtk objects using the property as an string, like it's handled the other properties that come form the settings, and merged this both different things with one mechanism, but in gjs, this are not so easy, like it's in python. search inside Gobject.object and inside Gobject.class:
https://people.gnome.org/~gcampagna/docs/GObject-2.0/index.html
Also from the web.

**Comment by jaszhix** [comment]
Ah, ok. I'm sure there's a workaround that could be approached. Do you want to modify the classes more to achieve the same functionality? It can't be all bad, one example - I noticed bugs in Cinnamon even today with spinbuttons - where with ITM's settings it doesn't always show 0 when the value is 0, and my change seemed to show the values every time. In some ways, they may have been relying on the Python APIs more for convenience, but had their own side effects as well.

**Comment by lestcape** [comment]
You see another alternative on this?
Your pull work?

**Comment by jaszhix** [comment]
Well my pull only fixes one class. We would still need to check all the others. I'm not familiar with GTK bindings in Python, so can't look at it the same way you are, I guess. We'll probably have to hack some things up to get it working. 

I also had this crazy idea of making a completely new app/UI for the settings, but that could be a time sink.

**Comment by lestcape** [comment]
I will work in spice.js, there are a lot of things that need a fix.. Specially the usage of threads in gjs. We have not multi threading. I will simulate the multi threading to update the online xlet, but this will required also a lot of work. 
Yes, in some moment of the history, will be good a reimplementation of this. But he, there are a lot of things to do... I will be happy, when i can move the setting to our settings and the gsettings schemas to our schemas, because this will work, without cinnamon.

**Comment by jaszhix** [comment]
Cool, sounds good. I'll probably keep investigating weird bugs. Like this one:

```sh
(gnome-shell:2174): Gjs-WARNING **: JS ERROR: Exception in callback for signal: icon-changed: TypeError: dev.getIndicatorIcon is not a function
NMApplet<._updateIcon@resource:///org/gnome/shell/ui/status/network.js:2017
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_emit@resource:///org/gnome/gjs/modules/signals.js:124
NMConnectionSection<._iconChanged@resource:///org/gnome/shell/ui/status/network.js:251
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
```

Or sometimes I try installing GNOME extensions, and actually saw different errors from other extensions as I updated my fork with the remote repo. One was the [Hide Top Bar](https://extensions.gnome.org/extension/545/hide-top-bar/) extension. That was a different install, I'll try to reproduce it tomorrow.

**Comment by lestcape** [comment]
We don't hacked yet the gnome panel, but can be easy hacked, adding the missing functionalities that our panels don' t have, it's see the gnome shell panel and add all public method  and properties to our panel (as alias) and fill back this to the gnome panel functionalities.

**Comment by jaszhix** [comment]
Yeah, another extension that got me looking at things differently was [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/), which moves all the activities widgets into a grouped window list bar. It'd be cool if we could get Cinnamon panels integrated that way. Not a priority now though.

**Comment by lestcape** [comment]
I agree, the dock it's the only popular feature that cinnamon don't have. some one wrote something like that, but won't work... Maybe reused this code will not be the idea as could conflict with the gnome shell dash and use some things similar to Dash to dock, will be more easy.

**Comment by lestcape** [comment]
Also we need to add repositories, to be easy install xlets from github.

**Comment by jaszhix** [comment]
Would it make sense to use the Spices website? Apparently they still host the applets on their server, but are just syncing them from Github. https://github.com/clefebvre/cinnamon-spices/commit/6db53bddab6d0034c91c589a83ef7c117c8720e2

**Comment by lestcape** [comment]
Yes, would make sence for now, but if we want to do different things later, will not have scene, we need to create our own repository, with the things that we want. In fact, will have a lot of scene a repository from the stock xlets.

**Comment by jaszhix** [comment]
I fixed the ComboBox options, but after much trial and error, not sure how to use set_active_iter correctly for the initial settings value. I tried adding a check inside [this](https://github.com/lestcape/Classic-Gnome/pull/9/commits/ebd9de305d7db5d5a163cef207a8bedc414d5179#diff-ecea8de8764e0053cee79745be59d3f5R1042) block, but I then saw:

```
(Classic Gnome:6600): Gtk-CRITICAL **: gtk_tree_model_get_path: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed

(Classic Gnome:6600): Gtk-CRITICAL **: gtk_cell_view_set_displayed_row: assertion 'GTK_IS_TREE_MODEL (cell_view->priv->model)' failed
```

But I ensured the Gtk.TreeIter was set inside the loop, which is the parameter of set_active_iter.

```
[boxed instance proxy GIName:Gtk.TreeIter jsobj@0x7ff4041bdd90 native@0x28b42c0]
```

So not sure. But the comboboxes can be set now and that updates the active iter correctly.

**Comment by jaszhix** [comment]
@lestcape Does this PR work look ok, or should I do something else?

**Comment by lestcape** [comment]
For me it's ok, can i merged it?

**Comment by jaszhix** [comment]
Yeah, sure.

**Pull request merged**
