### PR TITLE
Fix xlet installation, uninstallation

### PR DESCRIPTION
**Pull request by jaszhix**
Not sure why this is behaving differently now, but this should fix xlet installation.

### CODE REVIEW

**Comment by lestcape** [comment]
See the main page.

**Comment by jaszhix** [comment]
@lestcape Main page?

**Comment by lestcape** [comment]
Execute ./xlet-settings.js without parameters

**Comment by jaszhix** [comment]
Hm, this is all I see:

```
jason@jason-VirtualBox:~$ ~/.local/share/gnome-shell/extensions/classicGnome@lestcape/tools/xlet-settings.js applets 
\Loaded module: panels

Loaded module: main

Loaded module: settings

Loaded module: applets
```

**Comment by jaszhix** [comment]
Oops, copied the wrong part of the log, I didn't use "applets".

**Comment by lestcape** [comment]
Update the repository

**Comment by jaszhix** [comment]
Ahh, didn't see your last commit. Works, looks nice.

**Comment by jaszhix** [comment]
For some reason xlet settings (and the panel) settings don't have an effect anymore when changed, or even if Shell is restarted. Is this related to the schema renaming, you think?

**Comment by lestcape** [comment]
I see the effect, well the effect that i think you are speaking... (when they change his Stacks), there are not effect when change the whole page for the main page, but thats have not a solution.

**Comment by jaszhix** [comment]
I mean when you change an xlet setting, say you don't want category icons on the menu applet - toggling that doesn't have an effect for me anymore.

**Comment by lestcape** [comment]
Not, i don' t see the highly effect.

**Pull request merged**
