### PR TITLE
Fix the Cinnamon menu favorites pane width

### PR DESCRIPTION
**Pull request by jaszhix**
Not sure you like this, but for the default applets that we've modified anyway, I think it helps. I'm curious what differences in St/Clutter causes things like this between Cinnamon and Gnome Shell.

### CODE REVIEW

**Comment by lestcape** [comment]
I think it's not a difference of clutter of st, it's some thing relate with the theme... I think it's preferable do the same in the css than on the code, then... But in fact i'm not sure if really it's the theme and not other things.

**Comment by lestcape** [comment]
Well i know not what happen... this occurs, because we have loaded our theme and gnome shell have loaded his own theme both at the same time, but well... The question it's why gnome shell have a buggy theme???

See the error here: https://github.com/GNOME/gnome-shell/blob/7dd6b7f04f8619bb766e102802efcd0e41454015/data/theme/gnome-shell-high-contrast.css#L532

**Comment by lestcape** [comment]
It's fixed there: https://github.com/lestcape/Classic-Gnome/commit/766f8b10fb9ac1673c8f77599d748fa726fac5cf

We have now control of the gnome default theme, it's here:
https://github.com/lestcape/Classic-Gnome/commit/766f8b10fb9ac1673c8f77599d748fa726fac5cf#diff-8f20298adb88957c8d9bdb0f976c4fd0

**Comment by jaszhix** [comment]
Awesome, I'll test it out.

**Comment by lestcape** [comment]
Yes see the last comment: https://bugzilla.gnome.org/show_bug.cgi?id=700097

**Comment by lestcape** [comment]
If you see something that you don't want, search it in our gnome-shell default theme copy and change it to what you want.

**Comment by jaszhix** [comment]
Panel settings are working for me now, and so is the menu issue. Nicely done. :)

**Comment by jaszhix** [comment]
@lestcape I'm thinking about building a Spices registry server/client that uses Nodejs/Electron instead of GJS, and is cross-compatible with Cinnamon/Classic Gnome. What do you think?

**Comment by lestcape** [comment]
Thats will be good, but when you have the product what you will do with it? where you will hosting it?

**Comment by lestcape** [comment]
I have not more time, to do anything else... I evolved on a redesign of a php site with more that 10000 pages... I'm exhausting and we not finished yet.

**Comment by jaszhix** [comment]
I'm not sure yet, I guess its mostly academic for now. I will probably use a Linode VPS for the server using Django. Yeah I understand that, I haven't had much time outside work for FOSS stuff myself.

**Comment by lestcape** [comment]
I will continues with this, but i don't know when... If your server/client will report to you any benefits will be good, but if not, i thing it's a risk, because this is specific for spices format only.

**Comment by jaszhix** [comment]
I think it mainly would serve as a platform for anyone to have their work served to users, since Mint gave up on a normal third party extension system. Maybe it could handle other types of extensions, say in GNOME. I don't plan to make a website for this, its going to have a compact API and an Electron app that connects to it and installs extensions.

**Comment by lestcape** [comment]
Yes, but why you not speak first with clement? They could want this and will be good then... Make a software without have users it's lost the time to me...

**Comment by jaszhix** [comment]
I already let them know about it. I don't know what he thinks yet. I've been pushing for them to accept some ideas on how to fix the site so they stop hemorrhaging devs, but so far I've been ignored.

**Comment by lestcape** [comment]
Yes that’s the problem. They want stupid people that make works, and if the work look ok, they pay attentions if not, not. They want people that make works to him, not peoples that make work with him...

**Comment by jaszhix** [comment]
https://github.com/linuxmint/cinnamon-spices-applets/pull/254 <-- I mean, really? This messes up my whole process

**Comment by lestcape** [comment]
Why you think that i remove my extension...? Because there are not my extension anymore...

**Comment by jaszhix** [comment]
I'm keeping mine there because it'd affect all the ITM users. But yeah, its not a respectful approach.

**Comment by lestcape** [comment]
If all dev's will think in that way they can not do that... but it's not the case... So, if i'm who are wrong it's better not be part of that and not help to that type of things, because you are not helping anyone doing what you considered wrong and gains of the dev's... Devs are who make apps users not, the priority will be help devs then to create a place where more application can be developer, no help users, because they will directly helped when you help the devs...

**Comment by lestcape** [comment]
I need a query builder to create statistical reports in a survey system to my work, you know if there are one that can be used in php... I just know about this: http://querybuilder.js.org/

**Comment by jaszhix** [comment]
Ah, that's a problem I haven't had to solve before. I looked it up on [npmjs.com](https://npmjs.com) and the only front end option for this is the one you linked. I didn't look very thoroughly though so might see what else you can find there.

**Comment by lestcape** [comment]
There are other but for java... This is my current problem, because for years they generate individual page for any report, so there now more than 10000 pages and they are the site it's complete out of day... Just take a look of a site of 1980 http://encuestas.insp.mx/

**Comment by jaszhix** [comment]
I usually build UI stuff with React JS and often times will wrap custom components around prebuilt modules. Here's one that might help you - https://www.npmjs.com/package/react-querybuilder

If you're new to React I suggest giving it a try - https://facebook.github.io/react/

**Comment by lestcape** [comment]
Yes, i will be new, but not for now... Just i can not migrate the site to other technologies with this size. I need to reduce him and then migrate it whatever promise technology like react, but then just the important things... The problem with the querybuilder and with your reference it's that they don't allow really to do a column-column operation, just they do a column-constant operation. Also i need to do mathematics operations, but this will be to much for a query builder, so i need a query builder and a mathematics expression builder. I will create mathematics expressions first and then used it in a querybuilder to generate a full query... but it's a lot of works if i can not find a good approximation, but thanks...

**Comment by jaszhix** [comment]
Ah I see. Yeah, I was mostly thinking of just doing the form part in React, not redoing their site heh. Sorry I don't have any better leads on it, just not familiar type of project for me. I'll let you know if I come across something by chance.

**Pull request closed without merging**
